FROM rust:1.85 AS build

WORKDIR /app

COPY Cargo.toml Cargo.lock ./

COPY src ./src

RUN cargo build --release


FROM debian:bookworm-slim

WORKDIR /app

COPY --from=build /app/target/release/myapp .

EXPOSE 8080

CMD ["./myapp"]